import { assert, assertEquals } from '@std/assert';
import { createHandler } from '../../main.ts';
const root = await Deno.makeTempDir();
await Deno.writeTextFile(`${root}/index.html`, '<!doctype html><title>t</title>');
await Deno.writeFile(`${root}/data.bin`, Uint8Array.from({ length: 1000 }, (_, i) => i & 255));
await Deno.mkdir(`${root}/assets`);
await Deno.writeTextFile(`${root}/assets/main.js`, 'export {}');
await Deno.writeFile(`${root}/empty.txt`, new Uint8Array());
const mount = await Deno.makeTempDir();
await Deno.writeTextFile(`${mount}/f.json`, '{}');
const handler = createHandler({ root, mounts: { '/fixtures/': mount } });
const get = (path: string, headers: Record<string, string> = {}, method = 'GET') =>
  handler(new Request(`http://localhost${path}`, { headers, method }));
Deno.test('server: index, mime types, no-cache and nosniff headers', async () => {
  const index = await get('/');
  assertEquals(index.status, 200);
  assertEquals(index.headers.get('content-type'), 'text/html; charset=utf-8');
  assertEquals(index.headers.get('cache-control'), 'no-cache');
  assertEquals(index.headers.get('x-content-type-options'), 'nosniff');
  assert((await index.text()).includes('<title>'));
  const js = await get('/assets/main.js');
  assertEquals(js.headers.get('content-type'), 'text/javascript; charset=utf-8');
  await js.body?.cancel();
  const bin = await get('/data.bin');
  assertEquals(bin.headers.get('content-type'), 'application/octet-stream');
  assertEquals(bin.headers.get('content-length'), '1000');
  await bin.body?.cancel();
  const empty = await get('/empty.txt');
  assertEquals(empty.status, 200);
  assertEquals(empty.headers.get('content-length'), '0');
});
Deno.test('server: byte ranges for large video files, including suffix and open-ended ranges', async () => {
  const part = await get('/data.bin', { range: 'bytes=10-19' });
  assertEquals(part.status, 206);
  assertEquals(part.headers.get('content-range'), 'bytes 10-19/1000');
  assertEquals([...new Uint8Array(await part.arrayBuffer())], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]);
  const open = await get('/data.bin', { range: 'bytes=990-' });
  assertEquals(open.status, 206);
  assertEquals((await open.arrayBuffer()).byteLength, 10);
  const suffix = await get('/data.bin', { range: 'bytes=-5' });
  assertEquals(suffix.headers.get('content-range'), 'bytes 995-999/1000');
  assertEquals((await suffix.arrayBuffer()).byteLength, 5);
  const clipped = await get('/data.bin', { range: 'bytes=0-5000' });
  assertEquals(clipped.headers.get('content-range'), 'bytes 0-999/1000');
  await clipped.body?.cancel();
  const bad = await get('/data.bin', { range: 'bytes=2000-3000' });
  assertEquals(bad.status, 416);
  const head = await get('/data.bin', { range: 'bytes=0-1' }, 'HEAD');
  assertEquals(head.status, 206);
  assertEquals(head.body, null);
});
Deno.test('server: traversal, missing files, directories, methods, bad encoding and mounts', async () => {
  assertEquals((await get('/../deno.json')).status, 404);
  assertEquals((await get('/%2e%2e/%2e%2e/etc/passwd')).status, 404);
  assertEquals((await handler(new Request('http://localhost/x', { headers: { range: 'bytes=0-1' } }))).status, 404);
  assertEquals((await get('/missing.txt')).status, 404);
  assertEquals((await get('/assets')).status, 404);
  assertEquals((await get('/assets/')).status, 404);
  assertEquals((await get('/', {}, 'POST')).status, 405);
  assertEquals((await get('/%zz')).status, 400);
  const mounted = await get('/fixtures/f.json');
  assertEquals(mounted.status, 200);
  assertEquals(mounted.headers.get('content-type'), 'application/json');
  await mounted.body?.cancel();
  assertEquals((await get('/fixtures/../index.html')).status, 200);
});
